Repository ovh-ux/ovh-api-services, pull requests merged in 2019-06, with the labels that each got.

#176 feat: dedicatedCloud service packs
  src/dedicatedCloud/dedicatedCloud.service.js
  src/dedicatedCloud/servicePacks/dedicatedCloud-servicePacks.service.js
  src/dedicatedCloud/servicePacks/dedicatedCloud-servicePacks.v6.service.js
Labels: enhancement

#178 feat(dedicatedcloud.datacenter.zerto): on premises new routes
  src/dedicatedCloud/datacenter/zerto/dedicatedCloud-datacenter-zerto.v6.service.js
  src/dedicatedCloud/datacenter/zerto/single/dedicatedCloud-datacenter-zerto-single.v6.service.js
Labels: enhancement

#180 fix(zerto): add response transformation for default local vra network
  src/dedicatedCloud/datacenter/zerto/single/dedicatedCloud-datacenter-zerto-single.v6.service.js
Labels: bug

#181 feat: dedicatedCloud service packs
  src/dedicatedCloud/servicePacks/dedicatedCloud-servicePacks.v6.service.js
Labels: feature

#182 feat: add support for Iceberg
  src/dedicatedCloud/user/dedicatedCloud-user.iceberg.service.js
  src/dedicatedCloud/user/dedicatedCloud-user.service.js
Labels: feature

#183 feat(me.order): get bill
  src/me/order/me-order.v6.service.js
Labels: feature

#184 feat(me): add certificates route
  src/me/me.v6.service.js
Labels: feature

#186 fix: certificates response Array
  src/me/me.v6.service.js
Labels: bug

#185 feat(cloud.project.user.role): add put action
  src/cloud/project/user/role/cloud-project-user-role.v6.service.js
Labels: enhancement
