Repository ovh-ux/ovh-api-services, pull requests merged in 2019-08, with the labels that each got.

#209 feat(domain): options api addition
  src/api/domain/domain.service.js
  src/api/domain/options/domain-options.service.js
  src/api/domain/options/domain-options.v6.service.js
Labels: feature

#204 feat(spare): add spare management for telephony and xdsl
  src/api/telephony/spare/telephony-spare.service.js
  src/api/telephony/spare/telephony-spare.v6.service.js
  src/api/telephony/telephony.service.js
  src/api/xdsl/spare/xdsl-spare.service.js
  src/api/xdsl/spare/xdsl-spare.v6.service.js
  src/api/xdsl/xdsl.service.js
Labels: feature

#213 feat(order.catalog): add calls to public catalog
  src/api/order/catalog/order-catalog.service.js
  src/api/order/catalog/public/order-catalog-public.service.js
  src/api/order/catalog/public/order-catalog-public.v6.service.js
  src/api/order/order.service.js
Labels: feature

#215 feat(xdsl.modem): add reconfigure voip call for modem
  src/api/xdsl/modem/xdsl-modem.v6.service.js
Labels: feature

#217 build: bump @ovh-ux/ng-ovh-api-wrappers to v4.0.2
  package.json
Labels: build

#218 feat(xdsl.modem.exchange): add call for comfort exchange
  src/api/xdsl/modem/xdsl-modem.v6.service.js
Labels: feature

#210 feat: add new capabilities 2api endpoint
  src/api/vps/capabilities/vps-capabilities-aapi.service.js
  src/api/vps/capabilities/vps-capabilities.service.js
  src/api/vps/vps.service.js
Labels: feature

#220 feat(ovhproduct): add call to ovhProduct aapi
  src/api/ovhProduct/services.aapi.service.js
  src/api/ovhProduct/services.service.js
Labels: feature

#219 feat(xdsl.exchange): add rma call api
  src/api/xdsl/rma/xdsl-rma.service.js
  src/api/xdsl/rma/xdsl-rma.v6.service.js
  src/api/xdsl/xdsl.service.js
Labels: feature

#225 fix(deps): upgrade component-rollup-config to v6.0.2
  package.json
  yarn.lock
Labels: bug, dependencies
