Repository ovh-ux/ovh-api-services, pull requests merged in 2019-07, with the labels that each got.

#187 feat: handle new servicePack API path
  src/dedicatedCloud/dedicatedCloud.v6.service.js
Labels: feature

#189 build: add allow-root flag when using bower
  Makefile
Labels: build

#191 build: remove bower support
  .bowerrc
  .gitignore
  .npmignore
  Gruntfile.js
  Makefile
  README.md
  bower.json
  package.json
  yarn.lock
Labels: build

#194 feat(baremetal-bandwidth): add baremetal apis
  src/order/upgrade/baremetal-private-bandwidth/order-upgrade-baremetal-private-bandwidth.service.js
  src/order/upgrade/baremetal-private-bandwidth/order-upgrade-baremetal-private-bandwidth.v6.service.js
  src/order/upgrade/baremetal-public-bandwidth/order-upgrade-baremetal-public-bandwidth.service.js
  src/order/upgrade/baremetal-public-bandwidth/order-upgrade-baremetal-public-bandwidth.v6.service.js
  src/order/upgrade/order-upgrade.service.js
Labels: enhancement

#197 feat(billing): add aapi calls
  src/billing/autorenew/autorenew.service.js
  src/billing/autorenew/services/services.aapi.service.js
  src/billing/autorenew/services/services.service.js
  src/billing/billing.service.js
Labels: enhancement

#199 fix(kube-update): payload addition
  src/cloud/project/kube/cloud-project-kube.v6.service.js
Labels: bug

#202 fix(billing.autorenew): use non sws url as default
  src/billing/autorenew/services/services.aapi.service.js
Labels: bug

#203 Fix/support
  src/support/support.v6.service.js
Labels: bug, enhancement

#207 build(package.json): add both version and postversion scripts
  package.json
Labels: build

#208 build(package.json): set right package version
  package.json
Labels: build
