Repository ovh-ux/ovh-api-services, pull requests merged in 2019-10, with the labels that each got.

#239 feat(*): add enterprise db logs apis
  src/api/cloudDb/enterprise/logs/logs.v6.service.js
Labels: feature

#238 feat(telephony): add carrier sip cluster details
  src/api/telephony/carrierSip/carrier-sip.service.js
  src/api/telephony/carrierSip/clusterDetails/carrier-sip-clusterDetails.service.js
  src/api/telephony/carrierSip/clusterDetails/carrier-sip-clusterDetails.v6.service.js
Labels: feature

#241 feat(carrier-sip): add iceberg use for get all carrier sip lines
  src/api/telephony/carrierSip/carrier-sip.iceberg.js
  src/api/telephony/carrierSip/carrier-sip.service.js
Labels: feature

#242 docs: update readme file
  README.md
Labels: documentation

#240 feat(cloud.project.io): add resources
  src/api/cloud/project/cloud-project.service.js
  src/api/cloud/project/io/capabilities/cloud-project-io-capabilities.service.js
  src/api/cloud/project/io/capabilities/stream/cloud-project-io-capabilities-stream.service.js
  src/api/cloud/project/io/capabilities/stream/region/cloud-project-io-capabilities-stream-region.service.js
  src/api/cloud/project/io/capabilities/stream/region/cloud-project-io-capabilities-stream-region.v6.service.js
  src/api/cloud/project/io/cloud-project-io.service.js
  src/api/cloud/project/io/stream/cloud-project-io-stream.service.js
  src/api/cloud/project/io/stream/cloud-project-io-stream.v6.service.js
  src/api/cloud/project/io/stream/subscription/cloud-project-io-stream-subscription.service.js
  src/api/cloud/project/io/stream/subscription/cloud-project-io-stream-subscription.v6.service.js
  src/api/cloud/project/io/stream/token/cloud-project-io-stream-token.service.js
  src/api/cloud/project/io/stream/token/cloud-project-io-stream-token.v6.service.js
Labels: feature

#245 build(eslint): add markdown plugin
  .eslintrc.json
  package.json
  yarn.lock
Labels: build

#246 feat: add cloud lab api
  src/api/cloud/project/cloud-project.service.js
  src/api/cloud/project/lab/cloud-project-lab.service.js
  src/api/cloud/project/lab/cloud-project-lab.v6.service.js
Labels: feature

#248 feat(order): add followUp route
  src/api/me/order/me-order.v6.service.js
Labels: feature

#249 feat(api): add /webcoach
  src/api/webCoach/webCoach.service.js
  src/api/webCoach/webCoach.v6.service.js
Labels: enhancement

#247 feat(telephony.portability.document): add upload document for portability
  src/api/telephony/portability/document/telephony-portability-document.service.js
  src/api/telephony/portability/document/telephony-portability-document.v6.service.js
  src/api/telephony/portability/telephony-portability.service.js
Labels: feature

#250 feat(hosting): expose module list route through iceberg
  src/api/hosting/web/moduleList/web-moduleList.iceberg.service.js
  src/api/hosting/web/moduleList/web-moduleList.service.js
Labels: feature

#251 build(dev-deps): upgrade some dev dependencies
  package.json
  yarn.lock
Labels: dependencies

#252 feat(auth): add shouldDisplayMFAEnrollment & details routes
  src/api/auth/auth.v6.service.js
Labels: feature

#253 fix(vps): set different cache id for query request
  src/api/vps/images/available/vps-images-available.v6.service.js
Labels: bug

#254 feat(domain): add zone records
  src/api/domain/domain.service.js
  src/api/domain/zone/domain-zone.service.js
  src/api/domain/zone/domain-zone.v6.service.js
  src/api/domain/zone/record/domain-zone-record.service.js
  src/api/domain/zone/record/domain-zone-record.v6.service.js
Labels: enhancement

#256 fix(cloud.project.container.registry): remove extra param
  src/api/cloud/project/containerRegistry/cloud-project-containerRegistry.v6.service.js
Labels: bug
