Repository ovh-ux/ovh-api-services, pull requests merged in 2020-10, with the labels that each got.

#313 feat(pack.xdsl.move): add endpoint for service to delete
  src/api/pack/xdsl/move/pack-xdsl-move.v6.service.js
Labels: feature, question

#307 feat(cloud.project): remove io stream routes
  src/api/cloud/project/cloud-project.service.js
  src/api/cloud/project/io/capabilities/cloud-project-io-capabilities.service.js
  src/api/cloud/project/io/capabilities/stream/cloud-project-io-capabilities-stream.service.js
  src/api/cloud/project/io/capabilities/stream/region/cloud-project-io-capabilities-stream-region.service.js
  src/api/cloud/project/io/capabilities/stream/region/cloud-project-io-capabilities-stream-region.v6.service.js
  src/api/cloud/project/io/cloud-project-io.service.js
  src/api/cloud/project/io/stream/cloud-project-io-stream.service.js
  src/api/cloud/project/io/stream/cloud-project-io-stream.v6.service.js
  src/api/cloud/project/io/stream/subscription/cloud-project-io-stream-subscription.service.js
  src/api/cloud/project/io/stream/subscription/cloud-project-io-stream-subscription.v6.service.js
  src/api/cloud/project/io/stream/token/cloud-project-io-stream-token.service.js
  src/api/cloud/project/io/stream/token/cloud-project-io-stream-token.v6.service.js
Labels: breaking-change

#314 feat(cloud.project.ai.training): remove data and add registryId parameter
  src/api/cloud/project/ai/training/cloud-project-ai-training.service.js
  src/api/cloud/project/ai/training/data/cloud-project-ai-training-data.service.js
  src/api/cloud/project/ai/training/data/cloud-project-ai-training-data.v6.service.js
  src/api/cloud/project/ai/training/registry/cloud-project-ai-training-registry.v6.service.js
Labels: api-internal, breaking-change

#315 build(dev-deps): upgrade some dev dependencies
  package.json
  yarn.lock
Labels: dependencies
