Repository ovh-ux/ovh-api-services, pull requests merged in 2020-02, with the labels that each got.

#277 fix(cloud.project.container-registry): specify array response
  src/api/cloud/project/containerRegistry/cloud-project-containerRegistry.v6.service.js
  src/api/cloud/project/containerRegistry/plan/cloud-project-containerRegistry-plan.v6.service.js
Labels: bug

#279 feat(xdsl.modem): add endpoint to get price for modem exchange
  src/api/xdsl/modem/xdsl-modem.v6.service.js
Labels: feature

#280 feat(services): add form routes
  src/api/services/form/form.service.js
  src/api/services/form/form.v6.service.js
  src/api/services/services.service.js
Labels: feature

#281 feat(hosting): add extraSqlPerso path
  src/api/hosting/web/extraSqlPerso/extraSqlPerso.service.js
  src/api/hosting/web/extraSqlPerso/extraSqlPerso.v6.service.js
  src/api/hosting/web/web.service.js
Labels: enhancement

#282 feat(cloud): add pci deals route
  src/api/cloud/cloud.aapi.service.js
Labels: enhancement

#284 feat(dedicatedcloud-datacenter-backup): add backup offer capabilities
  src/api/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.v6.service.js
Labels: feature

#285 fix(*): add missing imports
  .eslintrc.json
  src/ovh-api-services.module.js
Labels: bug
