Repository ovh-ux/ovh-api-services, pull requests merged in 2021-06, with the labels that each got.

#316 refactor(telephony): remove unused aapi route
  src/api/telephony/line/telephony-line.aapi.service.js
  src/api/telephony/line/telephony-line.service.js
Labels: breaking-change

#326 fix(cloud.project.ai.job): remove non-existing endpoint
  src/api/cloud/project/ai/training/job/cloud-project-ai-training-job.v6.service.js
Labels: breaking-change, bug

#327 build(deps): upgrade lodash to v4.17.21
  package.json
  yarn.lock
Labels: dependencies
